### ISSUE TITLE
Sage Cells

### ISSUE THREAD

**Issue by rbeezer** [siefkenj/pretext-react#1]
*  Seems every Sage Cell is getting extra indentation.  See a simple one right before Example 4.2 of sample article.   Second line has about 30 extra spaces before the code.
* Sage Cell in Section 3 should follow "As a reader..." - using a different language ("R") so may have a different class.
* Example 4.2 is a torture-test of sorts.  Fix indentations, and the variable `a` is not remembered in a subsequent cell.  Neither is `c`, before and after the knowl.

**Comment by siefkenj** [comment]
> 



> * Seems every Sage Cell is getting extra indentation.  See a simple one right before Example 4.2 of sample article.   Second line has about 30 extra spaces before the code.

This is due to me having reformatted the HTML of that page specifically. It can be safely ignored.

> * Sage Cell in Section 3 should follow "As a reader..." - using a different language ("R") so may have a different class.

I've added a check for `sage-r` (in addition to my check for `sage-cell` and `sage-practice`. Are there any other classes I should look out for?

> * Example 4.2 is a torture-test of sorts.  Fix indentations, and the variable `a` is not remembered in a subsequent cell.  Neither is `c`, before and after the knowl.

It appears I didn't understand the `link` property on the sage cells correctly. I've posted on the `embedded_sagecell.js` Github to see if they have a workaround for the way I am setting up the cells. :-).

**Comment by siefkenj** [comment]
This should all be working now.
